apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
  labels: { app: frontend }
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels: { app: frontend }
  template:
    metadata:
      labels: { app: frontend }
    spec:
      containers:
        - name: frontend
          image: {{ include "todo-app.image" (dict "root" . "name" "todo-frontend") }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
          env:
            - name: API_BASE_URL
              value: "/api"
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          readinessProbe:
            httpGet: { path: /healthz, port: {{ .Values.frontend.port }} }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /healthz, port: {{ .Values.frontend.port }} }
            initialDelaySeconds: 10
            periodSeconds: 20
