apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: remediation-engine
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "delete", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: remediation-engine
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: remediation-engine
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: remediation-engine
  apiGroup: rbac.authorization.k8s.io
